In [ ]:
import sys
import numpy as np
np.set_printoptions(threshold=sys.maxsize)

In [21]:
n = 10    # num. observations
p = 5     # num. predictors
m = 10    # mc replicates
ϕ = 0.25  # prob. of dropping predictor  

# random design matrix
x = np.random.random((n, p))
print('Design matrix:\n\n', np.round(x, 3))

# bernoulli random predictor selection
d = np.random.binomial(1, 1-ϕ, (m, p))
print('\nDropout indicators:\n\n', d)

# design matrix w/ dropout
W = np.concatenate([d_*x for d_ in d])
print('\nDropout design matrix shape:\n\n', W.shape)
print('\nDropout design matrix:\n\n', np.round(W, 3))

Design matrix:

 [[0.594 0.534 0.968 0.36  0.624]
 [0.028 0.87  0.358 0.849 0.751]
 [0.813 0.47  0.884 0.157 0.702]
 [0.413 0.487 0.229 0.904 0.161]
 [0.761 0.921 0.567 0.539 0.016]
 [0.133 0.844 0.006 0.393 0.51 ]
 [0.908 0.322 0.254 0.151 0.299]
 [0.399 0.555 0.692 0.301 0.385]
 [0.026 0.85  0.641 0.373 0.822]
 [0.531 0.241 0.753 0.465 0.374]]

Dropout indicators:

 [[1 1 1 1 0]
 [0 0 1 0 1]
 [1 1 1 0 1]
 [1 1 1 0 1]
 [1 1 0 1 1]
 [1 1 1 1 1]
 [1 1 0 0 0]
 [1 1 1 1 1]
 [0 1 1 0 1]
 [1 1 1 1 1]]

Dropout design matrix shape:

 (100, 5)

Dropout design matrix:

 [[0.594 0.534 0.968 0.36  0.   ]
 [0.028 0.87  0.358 0.849 0.   ]
 [0.813 0.47  0.884 0.157 0.   ]
 [0.413 0.487 0.229 0.904 0.   ]
 [0.761 0.921 0.567 0.539 0.   ]
 [0.133 0.844 0.006 0.393 0.   ]
 [0.908 0.322 0.254 0.151 0.   ]
 [0.399 0.555 0.692 0.301 0.   ]
 [0.026 0.85  0.641 0.373 0.   ]
 [0.531 0.241 0.753 0.465 0.   ]
 [0.    0.    0.968 0.    0.624]
 [0.    0.    0.358 0.    0.751]
 [0.    0.    0.884 0.    0.702]
 [

In [20]:
def dropout(x: np.ndarray, m: int, ϕ: float) -> np.ndarray:
    """ Regularizes matrix x using dropout """
    
    assert(0 <= ϕ <= 1)  # r is a valid probability
    
    # perform dropout w/ bernoulli dist.
    _, p  = x.shape
    drop  = np.random.binomial(1, 1-ϕ, (m, p))
    x_out = np.concatenate([d*x for d in drop])
    
    return x_out

x_ = dropout(x, m, ϕ)

print(x_.shape)
print(np.round(x_, 3))

(100, 5)
[[0.13  0.537 0.197 0.    0.219]
 [0.788 0.982 0.565 0.    0.525]
 [0.224 0.734 0.366 0.    0.622]
 [0.155 0.298 0.985 0.    0.849]
 [0.819 0.815 0.676 0.    0.596]
 [0.5   0.859 0.773 0.    0.171]
 [0.183 0.211 0.669 0.    0.147]
 [0.67  0.795 0.58  0.    0.147]
 [0.394 0.538 0.468 0.    0.03 ]
 [0.071 0.042 0.257 0.    0.689]
 [0.13  0.537 0.197 0.    0.   ]
 [0.788 0.982 0.565 0.    0.   ]
 [0.224 0.734 0.366 0.    0.   ]
 [0.155 0.298 0.985 0.    0.   ]
 [0.819 0.815 0.676 0.    0.   ]
 [0.5   0.859 0.773 0.    0.   ]
 [0.183 0.211 0.669 0.    0.   ]
 [0.67  0.795 0.58  0.    0.   ]
 [0.394 0.538 0.468 0.    0.   ]
 [0.071 0.042 0.257 0.    0.   ]
 [0.13  0.    0.    0.31  0.219]
 [0.788 0.    0.    0.361 0.525]
 [0.224 0.    0.    0.524 0.622]
 [0.155 0.    0.    0.434 0.849]
 [0.819 0.    0.    0.3   0.596]
 [0.5   0.    0.    0.099 0.171]
 [0.183 0.    0.    0.808 0.147]
 [0.67  0.    0.    0.171 0.147]
 [0.394 0.    0.    0.773 0.03 ]
 [0.071 0.    0.    0.448 0.689]
 

In [ ]:
fun_list = [dropout]
fun_list[0](x, m, ϕ)

In [29]:
d_gen = ({'a': i} for i in np.linspace(0, 1, 101))
for d in d_gen:
    print(d)

{'a': 0.0}
{'a': 0.01}
{'a': 0.02}
{'a': 0.03}
{'a': 0.04}
{'a': 0.05}
{'a': 0.06}
{'a': 0.07}
{'a': 0.08}
{'a': 0.09}
{'a': 0.1}
{'a': 0.11}
{'a': 0.12}
{'a': 0.13}
{'a': 0.14}
{'a': 0.15}
{'a': 0.16}
{'a': 0.17}
{'a': 0.18}
{'a': 0.19}
{'a': 0.2}
{'a': 0.21}
{'a': 0.22}
{'a': 0.23}
{'a': 0.24}
{'a': 0.25}
{'a': 0.26}
{'a': 0.27}
{'a': 0.28}
{'a': 0.29}
{'a': 0.3}
{'a': 0.31}
{'a': 0.32}
{'a': 0.33}
{'a': 0.34}
{'a': 0.35000000000000003}
{'a': 0.36}
{'a': 0.37}
{'a': 0.38}
{'a': 0.39}
{'a': 0.4}
{'a': 0.41000000000000003}
{'a': 0.42}
{'a': 0.43}
{'a': 0.44}
{'a': 0.45}
{'a': 0.46}
{'a': 0.47000000000000003}
{'a': 0.48}
{'a': 0.49}
{'a': 0.5}
{'a': 0.51}
{'a': 0.52}
{'a': 0.53}
{'a': 0.54}
{'a': 0.55}
{'a': 0.56}
{'a': 0.5700000000000001}
{'a': 0.58}
{'a': 0.59}
{'a': 0.6}
{'a': 0.61}
{'a': 0.62}
{'a': 0.63}
{'a': 0.64}
{'a': 0.65}
{'a': 0.66}
{'a': 0.67}
{'a': 0.68}
{'a': 0.6900000000000001}
{'a': 0.7000000000000001}
{'a': 0.71}
{'a': 0.72}
{'a': 0.73}
{'a': 0.74}
{'a': 0.75}
{'a': 0.